### ISSUE TITLE
renaming the .cabal file

### ISSUE THREAD

**Issue by smunx** [solidsnakedev/plutarch-template#1]
I have renamed the file from plutarch-template.cabal to my-contract.cabal. I also changed the references in all the files.

This one in particular is giving me errors when I change the name from plutarch-template to my-contract (new name)
https://github.com/solidsnakedev/plutarch-template/blob/79f0c149bab6129329a49e07d26ce3ca920abcf1/plutarch-template.cabal#L134

```
Error:
error: builder for '/nix/store/pzzwkjs2himavbfr9y2qv1kz1hwi5gdh-haskell-project-plan-to-nix-pkgs.drv' failed with exit code 1;
       last 4 log lines:
       > Using index-state 2022-10-26T00:00:00Z
       > When using configuration(s) from /tmp/nix-build-haskell-project-plan-to-nix-pkgs.drv-1/tmp.L6pToYjKfx/cabal.project, the following errors occurred:
       > The package directory './.' does not contain any .cabal file.
       >
       For full logs, run 'nix log /nix/store/pzzwkjs2himavbfr9y2qv1kz1hwi5gdh-haskell-project-plan-to-nix-pkgs.drv'.

```
And the error goes away when I change the name back to plutarch-template and everything works fine.

**Comment by solidsnakedev** [comment]
`plutarch-template` is calling the library itself if you wish to change the name you must also change the names inside `plutarch-template.cabal`
https://github.com/solidsnakedev/plutarch-template/blob/79f0c149bab6129329a49e07d26ce3ca920abcf1/plutarch-template.cabal#L2

https://github.com/solidsnakedev/plutarch-template/blob/79f0c149bab6129329a49e07d26ce3ca920abcf1/plutarch-template.cabal#L121

https://github.com/solidsnakedev/plutarch-template/blob/79f0c149bab6129329a49e07d26ce3ca920abcf1/plutarch-template.cabal#L134
